classdef VSXReconInfo < matlab.mixin.Copyable
    properties
        mode (1,1) string {mustBeMember(mode, [...
            "replaceIntensity", ...
            "addIntensity", ...
            "multiplyIntensity", ...
            "replaceIQ", ...
            "accumIQ", ...
            "accumIQ_replaceIntensity", ...
            "accumIQ_addIntensity", ...
            "accumIQ_multiplyIntensity", ...
            "replaceIQ_normalize", ...
            "accumIQ_normalize", ...
            "replaceIQ_pages", ...
            "accumIQ_pages", ...
            ])} = "replaceIQ"
        txnum (1,1) VSXTX
        rcvnum (1,1) VSXReceive
        regionnum (1,1) 
        
    end
    methods
        function obj = VSXReconInfo(kwargs)
            arguments
                kwargs.?VSXReconInfo
            end
            for f = string(fieldnames(kwargs))'
                obj.(f) = kwargs.(f); 
            end
        end
    end
end