function [vUI, vEvent] = addSaveRF(vbuf_rx, vSeq)
arguments
    vbuf_rx (1,1) VSXRcvBuffer
    vSeq (1,:) VSXSeqControl = VSXSeqControl('command', 'noop', 'argument', 100/0.2); 
end
nm = "RFDataStore";
%% Process: saving data
save_rf_data = VSXProcess('classname', 'External', 'method', nm, 'Parameters',{ ...
    'srcbuffer','receive',...
    'srcbufnum', vbuf_rx,... 
    'srcframenum',0,...
    'dstbuffer','none'});

vUI = VSXUI( ...
'Control', {'auto','Style','VsPushButton','Label', 'SAVE RFData', 'Callback', str2func("do"+nm)}, ...
'Callback', cellstr(["do"+nm+"(varargin)", "global TOGGLE_"+nm+"; TOGGLE_"+nm+" = true; return;"]) ...
);

% save all RF Data
vEvent = VSXEvent('info', 'Save RF Data', 'process', save_rf_data, 'seqControl', vSeq);